import { User, Partner } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'user1',
    email: 'sophie.martin@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Sophie Martin',
    age: 28,
    city: 'Paris',
    bio: 'Passionnée de yoga et de running. Cherche un partenaire sportif pour partager mes sessions matinales!',
    sports: ['Yoga', 'Running', 'Natation'],
    favoriteSport: 'Yoga',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
    gender: 'female',
    lookingFor: 'male',
    isPremium: true,
    isOnline: true,
    hasPaid: true,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  },
  {
    id: 'user2',
    email: 'marc.dubois@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Marc Dubois',
    age: 32,
    city: 'Paris',
    bio: 'Entrepreneur et sportif du dimanche. Fan de fitness et de tennis. Let\'s match!',
    sports: ['Fitness', 'Tennis', 'Running'],
    favoriteSport: 'Fitness',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    gender: 'male',
    lookingFor: 'female',
    isPremium: false,
    isOnline: true,
    hasPaid: false,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  },
  {
    id: 'user3',
    email: 'julie.bernard@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Julie Bernard',
    age: 25,
    city: 'Lyon',
    bio: 'Addict de crossfit et de natation. Toujours partante pour de nouveaux défis sportifs!',
    sports: ['Fitness', 'Natation', 'Escalade'],
    favoriteSport: 'Fitness',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    gender: 'female',
    lookingFor: 'male',
    isPremium: false,
    isOnline: false,
    lastSeen: new Date(Date.now() - 3600000),
    hasPaid: false,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  },
  {
    id: 'user4',
    email: 'thomas.petit@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Thomas Petit',
    age: 29,
    city: 'Paris',
    bio: 'Coach sportif indépendant. Passionné de boxe et de running. En quête d\'une partenaire motivée!',
    sports: ['Boxe', 'Running', 'Fitness'],
    favoriteSport: 'Boxe',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    gender: 'male',
    lookingFor: 'female',
    isPremium: true,
    isOnline: true,
    hasPaid: true,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  },
  {
    id: 'user5',
    email: 'emma.lefebvre@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Emma Lefebvre',
    age: 26,
    city: 'Marseille',
    bio: 'Danseuse professionnelle et yogini. À la recherche d\'un partenaire pour explorer de nouvelles disciplines!',
    sports: ['Danse', 'Yoga', 'Running'],
    favoriteSport: 'Danse',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    gender: 'female',
    lookingFor: 'male',
    isPremium: false,
    isOnline: true,
    hasPaid: false,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  },
  {
    id: 'user6',
    email: 'alex.martin@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Alex Martin',
    age: 27,
    city: 'Paris',
    bio: 'Grimpeur passionné et runner du dimanche. En quête d\'aventures sportives!',
    sports: ['Escalade', 'Running', 'Tennis'],
    favoriteSport: 'Escalade',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400',
    gender: 'male',
    lookingFor: 'female',
    isPremium: false,
    isOnline: true,
    hasPaid: false,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  },
  {
    id: 'user7',
    email: 'chloe.dupont@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Chloé Dupont',
    age: 24,
    city: 'Paris',
    bio: 'Passionnée de danse et de fitness. Toujours de bonne humeur et motivée!',
    sports: ['Danse', 'Fitness', 'Yoga'],
    favoriteSport: 'Danse',
    photo: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400',
    gender: 'female',
    lookingFor: 'male',
    isPremium: false,
    isOnline: true,
    hasPaid: false,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  },
  {
    id: 'user8',
    email: 'lucas.bernard@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Lucas Bernard',
    age: 31,
    city: 'Paris',
    bio: 'Coach sportif professionnel. Spécialisé en musculation et nutrition.',
    sports: ['Fitness', 'Boxe', 'Running'],
    favoriteSport: 'Fitness',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400',
    gender: 'male',
    lookingFor: 'female',
    isPremium: true,
    isOnline: true,
    hasPaid: true,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  },
  {
    id: 'user9',
    email: 'marine.rousseau@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Marine Rousseau',
    age: 23,
    city: 'Paris',
    bio: 'Yogini le matin, danseuse le soir. À la recherche d\'un équilibre parfait!',
    sports: ['Yoga', 'Danse', 'Running'],
    favoriteSport: 'Yoga',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    gender: 'female',
    lookingFor: 'male',
    isPremium: false,
    isOnline: true,
    hasPaid: false,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  },
  {
    id: 'user10',
    email: 'maxime.laurent@gmail.com',
    password: 'password123',
    role: 'user',
    name: 'Maxime Laurent',
    age: 30,
    city: 'Paris',
    bio: 'Runner invétéré. J\'ai couru 5 marathons cette année. Qui veut m\'accompagner?',
    sports: ['Running', 'Natation', 'Escalade'],
    favoriteSport: 'Running',
    photo: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400',
    gender: 'male',
    lookingFor: 'female',
    isPremium: false,
    isOnline: true,
    hasPaid: false,
    swipedRight: [],
    swipedLeft: [],
    matches: [],
    badges: ['early_adopter'],
    stats: {
      totalMatches: 0,
      totalBookings: 0,
      totalSwipes: 0,
      joinedEvents: 0,
      dailySwipes: 0,
      lastSwipeResetDate: new Date().toISOString().split('T')[0]
    },
    blockedUsers: []
  }
];

export const MOCK_PARTNERS: Partner[] = [
  {
    id: 'partner1',
    email: 'contact@pulsefitness.com',
    password: 'partner123',
    role: 'partner',
    name: 'Pulse Fitness Club',
    type: 'Fitness',
    description: 'Salle de sport premium avec équipements dernier cri. Cours collectifs inclus.',
    photo: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    city: 'Paris',
    rating: 4.8,
    pricePerSession: 25,
    availableSlots: [
      { id: 's1', date: '2025-01-15', time: '09:00', available: true },
      { id: 's2', date: '2025-01-15', time: '11:00', available: true },
      { id: 's3', date: '2025-01-15', time: '14:00', available: true },
      { id: 's4', date: '2025-01-15', time: '18:00', available: true },
    ],
    bookedSlots: [],
    revenue: 0,
    reviews: []
  },
  {
    id: 'partner2',
    email: 'hello@zencenter.com',
    password: 'partner123',
    role: 'partner',
    name: 'Zen Yoga Center',
    type: 'Yoga',
    description: 'Centre de yoga et méditation. Ambiance zen et relaxante garantie.',
    photo: 'https://images.unsplash.com/photo-1588286840104-8957b019727f?w=400',
    city: 'Paris',
    rating: 4.9,
    pricePerSession: 20,
    availableSlots: [
      { id: 's5', date: '2025-01-15', time: '10:00', available: true },
      { id: 's6', date: '2025-01-15', time: '12:00', available: true },
      { id: 's7', date: '2025-01-15', time: '17:00', available: true },
      { id: 's8', date: '2025-01-15', time: '19:00', available: true },
    ],
    bookedSlots: [],
    revenue: 0,
    reviews: []
  },
  {
    id: 'partner3',
    email: 'info@aquaclub.com',
    password: 'partner123',
    role: 'partner',
    name: 'Aqua Swimming Club',
    type: 'Natation',
    description: 'Piscine olympique chauffée. Cours de natation tous niveaux.',
    photo: 'https://images.unsplash.com/photo-1600965962102-9d260a71890d?w=400',
    city: 'Lyon',
    rating: 4.7,
    pricePerSession: 18,
    availableSlots: [
      { id: 's9', date: '2025-01-15', time: '08:00', available: true },
      { id: 's10', date: '2025-01-15', time: '13:00', available: true },
      { id: 's11', date: '2025-01-15', time: '16:00', available: true },
    ],
    bookedSlots: [],
    revenue: 0,
    reviews: []
  }
];

export const ADMIN_USER = {
  id: 'admin1',
  email: 'admin@sportly.com',
  password: 'admin123',
  role: 'admin' as const,
  name: 'Admin Sportly'
};

export const AVAILABLE_BADGES = [
  {
    id: 'early_adopter',
    name: 'Early Adopter',
    description: 'Bienvenue dans la communauté Sportly!',
    icon: '🌟',
    unlocked: true
  },
  {
    id: 'on_fire',
    name: 'On Fire',
    description: 'Obtenez 5 matchs ou plus',
    icon: '🔥',
    unlocked: false,
    requirement: '5 matchs'
  },
  {
    id: 'yogi_master',
    name: 'Yogi Master',
    description: 'Réservez 3 cours de Yoga',
    icon: '🧘',
    unlocked: false,
    requirement: '3 réservations Yoga'
  },
  {
    id: 'fitness_fanatic',
    name: 'Fitness Fanatic',
    description: 'Réservez 3 cours de Fitness',
    icon: '💪',
    unlocked: false,
    requirement: '3 réservations Fitness'
  },
  {
    id: 'social_butterfly',
    name: 'Social Butterfly',
    description: 'Participez à 3 événements communautaires',
    icon: '🦋',
    unlocked: false,
    requirement: '3 événements'
  },
  {
    id: 'perfect_match',
    name: 'Perfect Match',
    description: 'Obtenez 10 matchs',
    icon: '💖',
    unlocked: false,
    requirement: '10 matchs'
  }
];
